package test;

import models.PersistenceAdmin;

/**@autor
 * Yeison Fernando Rodriguez Sanchez
*/

public class testTreeCompilate {
	private PersistenceAdmin persistence;

	public testTreeCompilate() {
		this.persistence = new PersistenceAdmin();
	}
	public void createTree() {
		String xml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><ROOT_TREE><DATAS_NODE_XML><TYPE_NODE_XML>CONFERENCE</TYPE_NODE_XML><ID_NODE_XML>root</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>TOPIC</TYPE_NODE_XML><ID_NODE_XML>java</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>TOPIC</TYPE_NODE_XML><ID_NODE_XML>java_Es</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>CONFERENCE</TYPE_NODE_XML><ID_NODE_XML>Conferencia_Es</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>LECTURER</TYPE_NODE_XML><ID_NODE_XML>juan David</ID_NODE_XML></DATAS_NODE_XML></NODE_CHILD><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>ATTENDEE</TYPE_NODE_XML><ID_NODE_XML>Juan</ID_NODE_XML></DATAS_NODE_XML></NODE_CHILD></NODE_CHILD></NODE_CHILD></NODE_CHILD><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>TOPIC</TYPE_NODE_XML><ID_NODE_XML>c++</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>TOPIC</TYPE_NODE_XML><ID_NODE_XML>C++_Grafos</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>CONFERENCE</TYPE_NODE_XML><ID_NODE_XML>Conferencia_Grafos</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>ATTENDEE</TYPE_NODE_XML><ID_NODE_XML>leonardo</ID_NODE_XML></DATAS_NODE_XML></NODE_CHILD></NODE_CHILD></NODE_CHILD></NODE_CHILD></ROOT_TREE>";
		persistence.getTreeConference(xml);
		persistence.printTree();
	}
	public void testGetExtencion() {
		System.out.println(persistence.getExtencionFile("/home/yeison/Downloads/IMAGENES DE FISICA EJER/4.jpeg"));
	}
	public void testTreePermission() {
		persistence.getTreePermissions("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><ROOT_TREE><DATAS_NODE_XML><TYPE_NODE_XML>ROOT</TYPE_NODE_XML><ID_NODE_XML>ROOT</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>USER</TYPE_NODE_XML><ID_NODE_XML>1ROOT</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>TOPIC</TYPE_NODE_XML><ID_NODE_XML>java_Es</ID_NODE_XML></DATAS_NODE_XML><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>CREATE</TYPE_NODE_XML><ID_NODE_XML>java_EsCREATE</ID_NODE_XML></DATAS_NODE_XML></NODE_CHILD><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>DELETE</TYPE_NODE_XML><ID_NODE_XML>java_EsDELETE</ID_NODE_XML></DATAS_NODE_XML></NODE_CHILD><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>REPORT</TYPE_NODE_XML><ID_NODE_XML>java_EsREPORT</ID_NODE_XML></DATAS_NODE_XML></NODE_CHILD></NODE_CHILD></NODE_CHILD><NODE_CHILD><DATAS_NODE_XML><TYPE_NODE_XML>USER</TYPE_NODE_XML><ID_NODE_XML>juan</ID_NODE_XML></DATAS_NODE_XML></NODE_CHILD></ROOT_TREE>");
		persistence.printTree();
	}
	public static void main(String[] args) {
		testTreeCompilate test=new testTreeCompilate();
		test.testTreePermission(); 
//		test.testGetExtencion();
//		test.createTree();
		
	}
}
